# Generated by Django 5.2.1 on 2025-06-14 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(default='Sin nombre', max_length=200, verbose_name='Nombre comercial')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='Razón social')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('persona_contacto', models.CharField(blank=True, max_length=200, verbose_name='Persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('forma_pago_preferida', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('credito', 'Crédito'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=20, verbose_name='Forma de pago preferida')),
                ('dias_credito', models.IntegerField(default=0, verbose_name='Días de crédito')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('ciudad_estado', models.CharField(blank=True, max_length=200, verbose_name='Ciudad/Estado')),
                ('categoria_productos', models.CharField(choices=[('ingredientes', 'Ingredientes'), ('bebidas', 'Bebidas'), ('utensilios', 'Utensilios'), ('empaque', 'Empaque'), ('limpieza', 'Limpieza'), ('equipos', 'Equipos')], default='ingredientes', max_length=20, verbose_name='Categoría de productos')),
                ('notas_adicionales', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente'), ('suspendido', 'Suspendido')], default='activo', max_length=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(editable=False, max_length=200)),
                ('contacto', models.CharField(blank=True, editable=False, max_length=200)),
                ('categoria', models.CharField(choices=[('ingredientes', 'Ingredientes'), ('bebidas', 'Bebidas'), ('utensilios', 'Utensilios'), ('empaque', 'Empaque'), ('limpieza', 'Limpieza'), ('equipos', 'Equipos')], default='ingredientes', editable=False, max_length=20)),
                ('notas', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ProveedorInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por unidad')),
                ('precio_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio con descuento')),
                ('cantidad_minima', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad mínima de compra')),
                ('tiempo_entrega_dias', models.IntegerField(default=1, verbose_name='Tiempo de entrega (días)')),
                ('activo', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, verbose_name='Notas específicas')),
            ],
            options={
                'verbose_name': 'Insumo por Proveedor',
                'verbose_name_plural': 'Insumos por Proveedor',
                'ordering': ['proveedor', 'insumo__categoria', 'insumo__nombre'],
            },
        ),
    ]
