# Generated by Django 5.2.3 on 2025-06-10 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('ingredientes', 'Ingredientes'), ('bebidas', 'Bebidas'), ('utensilios', 'Utensilios'), ('empaque', 'Empaque'), ('limpieza', 'Limpieza'), ('equipos', 'Equipos')], default='ingredientes', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente')], default='activo', max_length=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
