# Generated by Django 5.2.3 on 2025-06-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categoria_productos',
            field=models.CharField(choices=[('ingredientes', 'Ingredientes'), ('bebidas', 'Bebidas'), ('utensilios', 'Utensilios'), ('empaque', 'Empaque'), ('limpieza', 'Limpieza'), ('equipos', 'Equipos')], default='ingredientes', max_length=20, verbose_name='Categoría de productos'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad_estado',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ciudad/Estado'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_credito',
            field=models.IntegerField(default=0, verbose_name='Días de crédito'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='forma_pago_preferida',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('credito', 'Crédito'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=20, verbose_name='Forma de pago preferida'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(default='Sin nombre', max_length=200, verbose_name='Nombre comercial'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notas_adicionales',
            field=models.TextField(blank=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(choices=[('ingredientes', 'Ingredientes'), ('bebidas', 'Bebidas'), ('utensilios', 'Utensilios'), ('empaque', 'Empaque'), ('limpieza', 'Limpieza'), ('equipos', 'Equipos')], default='ingredientes', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='notas',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
