# Generated by Django 5.2.1 on 2025-06-14 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_insumo', to='restaurant.insumo'),
        ),
        migrations.AddField(
            model_name='proveedorinsumo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_proveedor', to='dashboard.proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='proveedorinsumo',
            unique_together={('proveedor', 'insumo')},
        ),
    ]
