# Generated by Django 5.2.3 on 2025-06-12 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del insumo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('pescados_mariscos', 'Pescados y Mariscos'), ('vegetales', 'Vegetales'), ('condimentos', 'Condimentos y Especias'), ('cereales', 'Cereales y Granos'), ('bebidas', 'Bebidas'), ('empaque', 'Material de Empaque'), ('limpieza', 'Productos de Limpieza'), ('utensilios', 'Utensilios'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('pza', 'Piezas'), ('caja', 'Cajas'), ('paquete', 'Paquetes'), ('metro', 'Metros'), ('rollo', 'Rollos')], default='pza', max_length=10, verbose_name='Unidad de medida')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock mínimo')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock actual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por unidad')),
                ('precio_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio con descuento')),
                ('cantidad_minima', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad mínima de compra')),
                ('tiempo_entrega_dias', models.IntegerField(default=1, verbose_name='Tiempo de entrega (días)')),
                ('activo', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, verbose_name='Notas específicas')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_insumo', to='dashboard.insumo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_proveedor', to='dashboard.proveedor')),
            ],
            options={
                'verbose_name': 'Insumo por Proveedor',
                'verbose_name_plural': 'Insumos por Proveedor',
                'ordering': ['proveedor', 'insumo__categoria', 'insumo__nombre'],
                'unique_together': {('proveedor', 'insumo')},
            },
        ),
    ]
