# Generated by Django 5.2.3 on 2025-06-12 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_insumo_proveedorinsumo'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_insumo', to='restaurant.insumo'),
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
    ]
