# Generated by Django 5.2.3 on 2025-07-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0004_cliente_cajaapertura_cajacierre_mesa_orden_ordenitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroquisLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_data', models.JSONField(help_text='Datos del layout en formato JSON')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='croquis_layout', to='accounts.sucursal')),
            ],
            options={
                'verbose_name': 'Layout de Croquis',
                'verbose_name_plural': 'Layouts de Croquis',
                'db_table': 'dashboard_croquis_layout',
            },
        ),
    ]
