# Generated by Django 5.2.4 on 2025-07-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_croquislayout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='activo',
            new_name='activa',
        ),
    ]
