# Generated by Django 5.2.4 on 2025-07-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_incidentevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='alert_type',
            field=models.CharField(blank=True, choices=[('primary', 'Informativa'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('danger', 'Error'), ('info', 'Información'), ('secondary', 'Secundaria')], default='info', max_length=20, null=True, verbose_name='Tipo de alerta'),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, choices=[('info-circle', 'Información'), ('check-circle', 'Completado'), ('exclamation-triangle', 'Advertencia'), ('exclamation-circle', 'Error'), ('bell', 'Notificación'), ('tools', 'Mantenimiento'), ('clipboard-check', 'Checklist'), ('tasks', 'Tareas'), ('camera', 'Evidencia'), ('bug', 'Incidente')], default='info-circle', max_length=30, null=True, verbose_name='Ícono'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enlace'),
        ),
    ]
