# Generated by Django 5.2.4 on 2025-07-15 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_notification_alert_type_notification_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Notas de verificación'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
    ]
