# Generated by Django 5.2.3 on 2025-07-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0001_initial'),
    ]

    operations = [
    ]
