# Generated by Django 5.2.3 on 2025-07-03 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_croquislayout'),
        ('mesero', '0002_auto_20250702_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_mesero', to='dashboard.mesa'),
        ),
    ]
