# Generated by Django 5.2.3 on 2025-07-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0003_alter_orden_mesa'),
        ('restaurant', '0003_merge_20250701_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ingrediente', 'Ingrediente'), ('preparacion', 'Preparación'), ('porcion', 'Porción'), ('extra', 'Extra'), ('coccion', 'Cocción'), ('temperatura', 'Temperatura')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de personalización',
                'verbose_name_plural': 'Tipos de personalización',
            },
        ),
        migrations.AlterField(
            model_name='orden',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_mesero', to='mesero.mesa'),
        ),
        migrations.CreateModel(
            name='OpcionPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('agregar', 'Agregar'), ('quitar', 'Quitar'), ('cambiar', 'Cambiar'), ('sin', 'Sin'), ('extra', 'Extra'), ('poco', 'Poco'), ('normal', 'Normal'), ('mucho', 'Mucho')], max_length=20)),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_personalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='mesero.tipopersonalizacion')),
            ],
            options={
                'verbose_name': 'Opción de personalización',
                'verbose_name_plural': 'Opciones de personalización',
            },
        ),
        migrations.CreateModel(
            name='OrdenItemPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicado', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('costo_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesero.opcionpersonalizacion')),
                ('orden_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizaciones', to='mesero.ordenitem')),
            ],
            options={
                'verbose_name': 'Personalización de item',
                'verbose_name_plural': 'Personalizaciones de items',
                'unique_together': {('orden_item', 'opcion')},
            },
        ),
        migrations.CreateModel(
            name='ProductoPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=False)),
                ('valor_por_defecto', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesero.opcionpersonalizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizaciones', to='restaurant.productoventa')),
            ],
            options={
                'verbose_name': 'Personalización de producto',
                'verbose_name_plural': 'Personalizaciones de productos',
                'ordering': ['orden', 'opcion__nombre'],
                'unique_together': {('producto', 'opcion')},
            },
        ),
    ]
