# Generated by Django 5.2.3 on 2025-07-04 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0004_tipopersonalizacion_alter_orden_mesa_and_more'),
        ('restaurant', '0003_merge_20250701_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionpersonalizacion',
            name='tipo_personalizacion',
        ),
        migrations.AlterModelOptions(
            name='opcionpersonalizacion',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Opción de personalización', 'verbose_name_plural': 'Opciones de personalización'},
        ),
        migrations.AlterModelOptions(
            name='ordenitempersonalizacion',
            options={'verbose_name': 'Personalización del item', 'verbose_name_plural': 'Personalizaciones de items'},
        ),
        migrations.AlterModelOptions(
            name='productopersonalizacion',
            options={'verbose_name': 'Personalización de producto', 'verbose_name_plural': 'Personalizaciones de productos'},
        ),
        migrations.RenameField(
            model_name='opcionpersonalizacion',
            old_name='activo',
            new_name='activa',
        ),
        migrations.AlterUniqueTogether(
            name='ordenitempersonalizacion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='opcionpersonalizacion',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='opcionpersonalizacion',
            name='costo_adicional',
        ),
        migrations.RemoveField(
            model_name='opcionpersonalizacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='productopersonalizacion',
            name='obligatorio',
        ),
        migrations.RemoveField(
            model_name='productopersonalizacion',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='productopersonalizacion',
            name='valor_por_defecto',
        ),
        migrations.AddField(
            model_name='opcionpersonalizacion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='opcionpersonalizacion',
            name='precio_extra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='opcionpersonalizacion',
            name='tipo',
            field=models.CharField(choices=[('quitar', 'Quitar ingrediente'), ('agregar', 'Agregar extra'), ('cambiar', 'Cambiar ingrediente'), ('nota', 'Nota especial')], default='quitar', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenitempersonalizacion',
            name='precio_aplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordenitempersonalizacion',
            name='valor',
            field=models.TextField(blank=True, help_text='Valor específico para notas o cambios', null=True),
        ),
        migrations.AddField(
            model_name='productopersonalizacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='TipoPersonalizacion',
        ),
        migrations.RemoveField(
            model_name='ordenitempersonalizacion',
            name='aplicado',
        ),
        migrations.RemoveField(
            model_name='ordenitempersonalizacion',
            name='costo_aplicado',
        ),
        migrations.RemoveField(
            model_name='ordenitempersonalizacion',
            name='notas',
        ),
    ]
