# Generated by Django 5.2.3 on 2025-07-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0005_remove_opcionpersonalizacion_tipo_personalizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
