# Generated by Django 5.2.3 on 2025-07-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0006_ordenitem_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
