# Generated by Django 5.2.4 on 2025-07-10 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0002_sistema_cuentas'),
        ('mesero', '0007_alter_mesa_numero'),
    ]

    operations = [
    ]
