# Generated by Django 5.2.4 on 2025-07-10 00:18

from django.db import migrations


def set_default_values(apps, schema_editor):
    """Set default values for existing records"""
    Orden = apps.get_model('mesero', 'Orden')
    
    # Set default values for existing orders
    Orden.objects.filter(cuenta_solicitada__isnull=True).update(cuenta_solicitada=False)
    Orden.objects.filter(cuenta_procesada__isnull=True).update(cuenta_procesada=False)
    Orden.objects.filter(ticket_generado__isnull=True).update(ticket_generado=False)


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0008_merge_0002_sistema_cuentas_0007_alter_mesa_numero'),
    ]

    operations = [
        migrations.RunPython(set_default_values, reverse_code=migrations.RunPython.noop),
    ]
