# Generated by Django 5.2.4 on 2025-07-10 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0009_auto_20250709_1818'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cuenta', to='mesero.orden')),
            ],
            options={
                'verbose_name': 'Notificación de Cuenta',
                'verbose_name_plural': 'Notificaciones de Cuenta',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
