# Generated by Django 5.2.3 on 2025-06-10 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Insumo',
                'verbose_name_plural': 'Categorías de Insumos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='CheckListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('apertura', 'Apertura'), ('cierre', 'Cierre'), ('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('inventario', 'Inventario')], max_length=20)),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item de CheckList',
                'verbose_name_plural': 'Items de CheckList',
                'ordering': ['tipo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('instrucciones', models.TextField()),
                ('tiempo_preparacion', models.IntegerField(help_text='Tiempo en minutos')),
                ('porciones', models.IntegerField(default=1)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('abreviacion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('basico', 'Insumo Básico'), ('compuesto', 'Insumo Compuesto'), ('elaborado', 'Insumo Elaborado')], default='basico', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('perecedero', models.BooleanField(default=False)),
                ('dias_vencimiento', models.IntegerField(blank=True, help_text='Días hasta vencimiento', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.categoriainsumo')),
                ('proveedor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.proveedor')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.unidadmedida')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('transferencia', 'Transferencia')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.TextField()),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.insumo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
            },
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('disponible', models.BooleanField(default=True)),
                ('es_promocion', models.BooleanField(default=False)),
                ('precio_promocion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio_promocion', models.DateField(blank=True, null=True)),
                ('fecha_fin_promocion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.categoriaproducto')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.receta')),
            ],
            options={
                'verbose_name': 'Producto de Venta',
                'verbose_name_plural': 'Productos de Venta',
            },
        ),
        migrations.CreateModel(
            name='CheckListEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.checklistitem')),
            ],
            options={
                'verbose_name': 'Ejecución de CheckList',
                'verbose_name_plural': 'Ejecuciones de CheckList',
                'unique_together': {('item', 'sucursal', 'fecha', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cantidad_reservada', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fecha_ultimo_movimiento', models.DateTimeField(auto_now=True)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.insumo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sucursal')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'unique_together': {('sucursal', 'insumo', 'lote')},
            },
        ),
        migrations.CreateModel(
            name='RecetaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='restaurant.receta')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Recetas',
                'unique_together': {('receta', 'insumo')},
            },
        ),
    ]
