# Generated by Django 5.2.3 on 2025-07-01 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='calorias',
            field=models.IntegerField(blank=True, default=0, help_text='Calorías por porción', null=True),
        ),
        migrations.CreateModel(
            name='ProductoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_asociadas', to='restaurant.productoventa')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_asociados', to='restaurant.receta')),
            ],
            options={
                'verbose_name': 'Receta de producto',
                'verbose_name_plural': 'Recetas de productos',
                'ordering': ['producto', 'orden'],
                'unique_together': {('producto', 'receta')},
            },
        ),
    ]
