# Generated by Django 5.2.3 on 2025-06-12 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoCompuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad del componente necesaria', max_digits=10)),
                ('orden', models.IntegerField(default=0, help_text='Orden en la lista de componentes')),
                ('insumo_componente', models.ForeignKey(limit_choices_to={'tipo': 'basico'}, on_delete=django.db.models.deletion.CASCADE, related_name='usado_en_compuestos', to='restaurant.insumo')),
                ('insumo_compuesto', models.ForeignKey(limit_choices_to={'tipo': 'compuesto'}, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='restaurant.insumo')),
            ],
            options={
                'verbose_name': 'Componente de Insumo Compuesto',
                'verbose_name_plural': 'Componentes de Insumos Compuestos',
                'ordering': ['orden', 'insumo_componente__nombre'],
                'unique_together': {('insumo_compuesto', 'insumo_componente')},
            },
        ),
    ]
