# Generated by Django 5.2.3 on 2025-06-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_insumocompuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad_producida',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cantidad que se produce de este insumo compuesto', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del insumo'),
        ),
    ]
