# Generated by Django 5.2.3 on 2025-07-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_productoventa_calorias_productoreceta'),
        ('restaurant', 'fix_receta_cascade'),
    ]

    operations = [
    ]
