# Generated by Django 5.2.4 on 2025-07-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_merge_20250701_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='nombre',
            field=models.CharField(default='Receta', max_length=200),
            preserve_default=False,
        ),
    ]
