# Generated by Django 5.2.3 on 2025-06-13 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_insumo_cantidad_producida_insumo_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoElaborado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad del componente necesaria', max_digits=10)),
                ('orden', models.IntegerField(default=0, help_text='Orden en la lista de componentes')),
                ('tiempo_preparacion_minutos', models.IntegerField(default=0, help_text='Tiempo adicional de preparación en minutos')),
                ('instrucciones', models.TextField(blank=True, help_text='Instrucciones específicas para este componente')),
                ('insumo_componente', models.ForeignKey(limit_choices_to={'tipo': 'compuesto'}, on_delete=django.db.models.deletion.CASCADE, related_name='usado_en_elaborados', to='restaurant.insumo')),
                ('insumo_elaborado', models.ForeignKey(limit_choices_to={'tipo': 'elaborado'}, on_delete=django.db.models.deletion.CASCADE, related_name='componentes_elaborados', to='restaurant.insumo')),
            ],
            options={
                'verbose_name': 'Componente de Insumo Elaborado',
                'verbose_name_plural': 'Componentes de Insumos Elaborados',
                'ordering': ['orden', 'insumo_componente__nombre'],
                'unique_together': {('insumo_elaborado', 'insumo_componente')},
            },
        ),
    ]
