# Generated by Django 5.2.4 on 2025-07-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_receta_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único para identificar la configuración', max_length=100, unique=True)),
                ('valor', models.TextField(blank=True, help_text='Valor de la configuración (puede ser JSON)', null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la configuración', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuraciones del sistema',
                'ordering': ['nombre'],
            },
        ),
    ]
