# Generated by Django 5.2.3 on 2025-06-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_insumoelaborado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único para la categoría', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría')),
                ('activa', models.BooleanField(default=True, help_text='Si la categoría está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Receta',
                'verbose_name_plural': 'Categorías de Recetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría de la receta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.categoriareceta'),
        ),
    ]
