# Generated by Django 5.2.4 on 2025-07-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_incidenthistory_incidentevidence'),
        ('dashboard', '0010_incidentevidence_incidenthistory'),
        ('dashboard', '0011_incidenthistory'),
    ]

    operations = [
    ]
